language: php

services:
    - redis-server

php:
  - 5.3
  - 5.4
  - 5.5
  - hhvm
  - hhvm-nightly

matrix:
    allow_failures:
        - php: hhvm-nightly

before_script:
    - composer install --dev
    - cp .env.dist .env

script: ./vendor/bin/phpunit
